Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp. Затем поделите a_centered_sp на N-1, где N - число наблюдений.

In [2]:
import numpy as np

In [3]:
a = np.array ([[1, 6],
              [2, 8],
              [3, 11],
              [3, 10],
              [1, 7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [4]:
mean_a = np.array (a.mean(axis = 0))
mean_a

array([2. , 8.4])

In [5]:
a_centered = a - mean_a

In [6]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [10]:
b,c = np.hsplit(a_centered, 2)

In [11]:
b

array([[-1.],
       [ 0.],
       [ 1.],
       [ 1.],
       [-1.]])

In [12]:
c

array([[-2.4],
       [-0.4],
       [ 2.6],
       [ 1.6],
       [-1.4]])

In [19]:
a_centered_sp = b.flatten() @ c.flatten()
a_centered_sp

8.0

In [20]:
a.shape

(5, 2)

In [21]:
rows, columns = a.shape

In [22]:
rows

5

In [23]:
d = a_centered_sp / (rows - 1)
d

2.0